# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["engine"]
default-members = ["engine"]

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
