[package]
name = "lambda_space"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
nalgebra = "0.31.0"
derive-new = "0.5.9"
imgui = "0.8.2"
